AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda Function for ETL Pipeline (S3 deployment package)

Parameters:
  RawBucketName:
    Type: String
    Description: Name of the raw data S3 bucket
  CuratedBucketName:
    Type: String
    Description: Name of the curated data S3 bucket

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ana-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ETLLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ana-etl-func
      Runtime: python3.9
      Handler: lambda_etl.lambda_handler   # Matches module in zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: ana-lambda-code          # Bucket containing your lambda_etl.zip
        S3Key: lambda_etl.zip
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          RAW_BUCKET: !Ref RawBucketName
          CURATED_BUCKET: !Ref CuratedBucketName

Outputs:
  LambdaFunctionName:
    Description: ETL Lambda function name
    Value: !Ref ETLLambdaFunction
  LambdaFunctionArn:
    Description: ETL Lambda ARN
    Value: !GetAtt ETLLambdaFunction.Arn
