AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Buckets for ETL Pipeline

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ana-raw-dev-prajakta

  CuratedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ana-curated-dev

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ana-logs-dev

Outputs:
  RawBucketName:
    Value: !Ref RawDataBucket
  CuratedBucketName:
    Value: !Ref CuratedDataBucket
  LogsBucketName:
    Value: !Ref LogsBucket
